### ISSUE TITLE
ownKeys trap handler

### ISSUE THREAD

**Issue by jasisk** [gas-buddy/l10n#1]
I'd give a dollar to anyone who implements an `ownKeys` trap handler in the l10n proxy.

**Comment by djMax** [comment]
for what purpose?

**Comment by jasisk** [comment]
> for what purpose?

(This was more a note for myself.)

To enable iteration.

Specifically, I wanted to select a nested template at random.

I can currently do it like this:
``` js
const keys = ["key1", "key2", "key3"];
const key = keys[Math.floor(Math.random() * keys.length)];
const string = l10n.Parent[key]();
```

But I can't do this:
``` js
const keys = Object.keys(l10n.Parent);
const key = keys[Math.floor(Math.random() * keys.length)];
const string = l10n.Parent[key]();
```

or this:
``` js
const tmplFns = Object.values(l10n.Parent);
const template = tmplFns[Math.floor(Math.random() * strings.length)];
const string = template.apply(l10n.Parent); // not sure I'll be able to do this anyway because of the binding requirement
```

**Comment by djMax** [comment]
I think the easier thing might be to make this array-aware. So if a lookup yields an array it just does the randomization for you. I can do that after Felix graduation.

**Comment by djMax** [comment]
Added array support in 0.2.0.
